### ISSUE TITLE
Typescript CallEffect is any

### ISSUE THREAD

**Issue by RXminuS** [redux-saga/redux-saga#1504]
I can't imagine I'm the first one to ask this but I couldn't find anything in the issues.

We're in the process of moving our app form Flow to Typescript and one thing that bothers me is that the return values of the 'call' effect aren't strongly typed. I don't know if it's because I'm using the function wrong or if we maybe need to update the Typings in redux-saga.

If I call my function `getRes() : Res` like this
```ts
const res = yield call(getRes)
// typeof res == any
```

But if I call my function like this (since Typescript 2.8)
```ts
const res : ReturnType<typeof getRes> = yield call(getRes)
// typeof res == Res
```
it works fine. However, it's a bit annoying to have to manually type my return value if the return value of the function is known by call, just not sure how that works with generators & yields. Is this the way to do it? Can I fix / update something in the typings?

**Comment by shinima** [comment]
This is a limitation of TypeScript on inferring types of `yield` expression.  You could see Microsoft/TypeScript#10509 for more detail.

IMHO, inferring types of `yield` expression accurately (infer every `yield` with correct type) is very difficult for TypeScript, and this feature has limited usages (only coroutine drivers need this feature).  Annotating types manually seems the only working approach for now.

**Comment by Andarist** [comment]
@RXminuS Out of curiosity - is flow able to infer those?

**Comment by aikoven** [comment]
Note that the type of value returned from `yield` depends on the runtime that runs the generator. So there's no way for a compiler to infer it without a hint.

That hint could be a function on types, that tells you the type of the result you get back if you `yield` value of given type (the type of the effect in our case). 

The interesting thing is that TypeScript already has the way to express this kind of function, called Conditional Types. With it we can turn effect type to the result type, something like:

```ts
type EffectResult<T extends Effect> = 
  T extends CallEffect<infer R> ? R :
  T extends ForkEffect<infer R> ? Task<R> :
  ...
```

Alas, there's no way currently to attach this to a generator. And I don't think that there'll be one soon, since the use of generators is still niche.

We could do it manually, like this:

```ts
const effect = call(...);
const result: EffectResult<typeof effect> = yield effect;
```

Though it looks really ugly.

Maybe we could make a TSLint plugin that could insert that code automatically to get type checking.

**Comment by henrikra** [comment]
Looks like I am going to use something else than redux-saga because it doesn't work with TS :/

**Comment by Andarist** [comment]
Seems like this is not actionable right now on our side, so gonna need to close this.

**Comment by alexfoxgill** [comment]
it's a limitation of generators. it is impossible to know what a generator will yield without running the program. for example

```
function* generator() {
    var bar = yield 'foo';
}

const iterator = generator()
const foo = iterator.next()
const nextThing = iterator.next(1)
```

here `bar` is `1`

**Comment by JoshMcCullough** [comment]
@henrikra You don't have to use generators/yield....(correct me if my solution is not pretty much the same)...

```
    // with generator/yield
    const { response, error } = yield call(Api.create, action.payload.project);

    // promises
    Api.create(action.payload.project)
        .then(({response, error}) => {
           
            // ... do stuff, args are properly typed
        });
```

**Comment by voliva** [comment]
@JoshMcCullough The example you provided isn't technically wrong, but keep in mind that the code in your saga should not call side effects directly, but through `call` (and letting the middleware handle the side effect for you). This will later help you with testing your sagas.

Check the [official doc](https://redux-saga.js.org/docs/basics/DeclarativeEffects.html) for more info

**Comment by lukescott** [comment]
https://devblogs.microsoft.com/typescript/announcing-typescript-3-6-beta/

> Additionally, generators just assumed the type of yield was always any.
> ...
> In TypeScript 3.6, the checker now knows that the correct type for curr.value should be string in our first example, and will correctly error on our call to next() in our last example. This is thanks some changes in the Iterator and IteratorResult type declarations to include a few new type parameters, and to a new type that TypeScript uses to represent generators called the Generator type.

It looks like in 3.6 it will be possible to do this. @Andarist Can this be reopened?

**Comment by henrikra** [comment]
To my understanding the new updates in TS 3.6 don't really help with redux-saga generators. Or am I wrong? 🤔

**Comment by carneiror** [comment]
> To my understanding the new updates in TS 3.6 don't really help with redux-saga generators. Or am I wrong? 🤔

I just tested with typescript@3.6.1-rc and yield is still returning `any`

**Comment by henrikra** [comment]
😢

**Comment by lukescott** [comment]
As far as I can tell, the main issue linked from a redux-saga issue has been fixed:

https://github.com/microsoft/TypeScript/issues/2873

@carneiror can you share what you tried?

As far as I can tell the `Generator<TYield, TReturn, TNext>` type should work. Specifically `TNext` is what specifies what `yield` gets back from `generator.next(...)`.

The redux-saga types would have to be changed to use `Generator`.

**Comment by carneiror** [comment]
I tried a similar example as shown here: https://github.com/microsoft/TypeScript/pull/3031

```
function* g(): Iterable<string> {
  const result = yield "";
  console.log(result);
}
```
With the latest RC version (3.6.1-rc)`result` is still `any` for me :(

**Comment by voliva** [comment]
As far as I understand, the changes in TS@3.6 allow for more type safety around generators - So if you declare a generator function that yields strings and expects numbers, you can only use that generator by passing in numbers and receiving strings.

The example in their release notes shows this behaviour:
```ts
function* foo() {
    let x: string = yield {}; // Yields {}, expects string
    console.log(x.toUpperCase());
    return 3; // Returns number
}
// typeof foo = Generator<{}, number, string>

let x = foo();
x.next(); // first call to 'next' is always ignored
x.next(42); // error! 'number' is not assignable to 'string'
```

But, it doesn't work the other way around: TS still doesn't have any way to know the type that the yield will "return", as the generator function can be used in many places around. So if you don't enforce a type to the `yield` assignment:
```ts
function* foo() {
    let x = yield {}; // typeof x = any
    console.log(x.toUpperCase());
    return 3;
}
// typeof foo = Generator<{}, number, any>
```

Which is what redux-saga would need. We know that, by contract, `yield call(fn, ...args);` will give us whatever value `fn` returns, but at the point in time TS is defining the type of the generator it has no way of knowing that (since it fully depends on the code that works with that iterator)

(at least, as far as I understand)

**Comment by ismaelsousa** [comment]
https://github.com/agiledigital/typed-redux-saga
use this lib
before 
`function* fetchUser(action) {
  // `user` has type any
  const user = yield call(Api.fetchUser, action.payload.userId);
  ...
}
`
after
`function* fetchUser(action) {
  // Note yield is replaced with yield*
  // `user` now has type User, not any!
  const user = yield* call(Api.fetchUser, action.payload.userId);
  ...
}`
